In [1]:
#Q1 Consider the following Arrays:
import numpy as np
import pandas as pd
arr1 = np.array([[1, 1, 0], [9, 7, 8], [6, 8, 4]])

arr2 = np.array([[[5, 2, 1], [2, 1, 8]], [[1, 2, 3], [4, 5, 6]]])

#Find output of the following:

arr2[0]

array([[5, 2, 1],
       [2, 1, 8]])

In [2]:
arr2[1] [1]

array([4, 5, 6])

In [3]:
arr1[:2, -1]


array([0, 8])

In [4]:
arr1[:,2:]



array([[0],
       [8],
       [4]])

In [5]:
arr1[-1,:]


array([6, 8, 4])

In [6]:
#Consider the following Data Frame:

Data = {'State': ['Delhi', 'Mumbai', 'Bangalore', 'Delhi', 'Kolkata', 'Pune'],
 'Year': [2001, 1992, 1995, 2005, 1992, 2001],
 'Population': [5.2, 1.8, 1.5, 7.8, 1.2, 2.5]
       }
df = pd.DataFrame(Data)
Data

#Answer the following:

#a. Rename the indexes as “One”, “Two”, “Three”, “Four”, “Five”, “Six”
#b. Add another column in the Data Frame “Extra” having values True corresponding to state ‘Delhi’ else False.
#c. Name all the states with Population more than 2.
#d. Drop rows ‘Three’ and ‘Six’.


{'State': ['Delhi', 'Mumbai', 'Bangalore', 'Delhi', 'Kolkata', 'Pune'],
 'Year': [2001, 1992, 1995, 2005, 1992, 2001],
 'Population': [5.2, 1.8, 1.5, 7.8, 1.2, 2.5]}

In [7]:
Data = {'State': ['Delhi', 'Mumbai', 'Bangalore', 'Delhi', 'Kolkata', 'Pune'],
 'Year': [2001, 1992, 1995, 2005, 1992, 2001],
 'Population': [5.2, 1.8, 1.5, 7.8, 1.2, 2.5],
       }

df = pd.DataFrame(Data)
df


State  Year  Population
0      Delhi  2001         5.2
1     Mumbai  1992         1.8
2  Bangalore  1995         1.5
3      Delhi  2005         7.8
4    Kolkata  1992         1.2
5       Pune  2001         2.5

In [8]:
#a. Rename the indexes as “One”, “Two”, “Three”, “Four”, “Five”, “Six”
Index = ['One', 'Two', 'Three', 'Four', 'Five', 'Six']
df = pd.DataFrame(Data, index = [Index])
df

State  Year  Population
One        Delhi  2001         5.2
Two       Mumbai  1992         1.8
Three  Bangalore  1995         1.5
Four       Delhi  2005         7.8
Five     Kolkata  1992         1.2
Six         Pune  2001         2.5

In [9]:
#b. Add another column in the Data Frame “Extra” having values True corresponding to state ‘Delhi’ else False.
df2 = pd.DataFrame(df, columns = ['State', 'Year', 'Population', 'Extra'])
df2['Extra'] = df2['State'] == 'Delhi'
df2

State  Year  Population  Extra
One        Delhi  2001         5.2   True
Two       Mumbai  1992         1.8  False
Three  Bangalore  1995         1.5  False
Four       Delhi  2005         7.8   True
Five     Kolkata  1992         1.2  False
Six         Pune  2001         2.5  False

In [10]:
#c. Name all the states with Population more than 2.
Pop = df2[df2.Population > 2]
Pop

State  Year  Population  Extra
One   Delhi  2001         5.2   True
Four  Delhi  2005         7.8   True
Six    Pune  2001         2.5  False

In [11]:
Pop.State


One     Delhi
Four    Delhi
Six      Pune
Name: State, dtype: object

In [12]:
#d. Drop rows ‘Three’ and ‘Six’.
drop3 = df2.drop('Three')
drop3

/var/folders/l7/qy63p4fn1r97qfbcpj42tsp80000gn/T/ipykernel_40436/1933575260.py:2: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  drop3 = df2.drop('Three')


State  Year  Population  Extra
One     Delhi  2001         5.2   True
Two    Mumbai  1992         1.8  False
Four    Delhi  2005         7.8   True
Five  Kolkata  1992         1.2  False
Six      Pune  2001         2.5  False

In [13]:
drop6 = drop3.drop('Six')
drop6

/var/folders/l7/qy63p4fn1r97qfbcpj42tsp80000gn/T/ipykernel_40436/1891032251.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  drop6 = drop3.drop('Six')


State  Year  Population  Extra
One     Delhi  2001         5.2   True
Two    Mumbai  1992         1.8  False
Four    Delhi  2005         7.8   True
Five  Kolkata  1992         1.2  False

In [14]:
#Q5 Consider the following Series:

SR = pd.Series(([8, -2, 6, 4, 3, 0, 6, -1]), index = [0, 3, 4, 6,  7, 10, 12, 14])

#Find the output of the following:

#SR.rank()
#SR.rank(method = ‘first’)
#SR.rank(ascending = False, method = ‘min’)
#SR.reindex(range(6), method = ‘ffill’)
#SR.replace({-2: np.nan, 6: 0})


In [15]:
SR.rank()

0     8.0
3     1.0
4     6.5
6     5.0
7     4.0
10    3.0
12    6.5
14    2.0
dtype: float64

In [16]:
SR.rank(method = 'first')

0     8.0
3     1.0
4     6.0
6     5.0
7     4.0
10    3.0
12    7.0
14    2.0
dtype: float64

In [17]:
SR.rank(ascending = False, method = 'min')

0     1.0
3     8.0
4     2.0
6     4.0
7     5.0
10    6.0
12    2.0
14    7.0
dtype: float64

In [18]:
SR.reindex(range(6), method = 'ffill')

0    8
1    8
2    8
3   -2
4    6
5    6
dtype: int64

In [19]:
SR.replace({-2: np.nan, 6: 0})

0     8.0
3     NaN
4     0.0
6     4.0
7     3.0
10    0.0
12    0.0
14   -1.0
dtype: float64

In [20]:
#Q7 Consider the following list:

x1 = [32, 21, 65, 89, 33, 23, 22, 40, 21, 32, 56, 45, 44, 38, 52]

#From ‘x1’ create an ndarray ‘x2’ with 5 rows and 3 columns.
#Find Mean, Variance, Median of data in x2 along the rows.
#Find cumulative sum of rows in ‘x2’.
#Sort the data in ‘x2’ along the columns.
#Replace values greater than 40 in ‘x2’ with 0 using ‘where’ function.




In [21]:
x1


[32, 21, 65, 89, 33, 23, 22, 40, 21, 32, 56, 45, 44, 38, 52]

In [22]:
#From ‘x1’ create an ndarray ‘x2’ with 5 rows and 3 columns.
x2 = np.array([x1]).reshape((5, 3))
x2

array([[32, 21, 65],
       [89, 33, 23],
       [22, 40, 21],
       [32, 56, 45],
       [44, 38, 52]])

In [23]:
#Find Mean, Variance, Median of data in x2 along the rows.
np.mean(x2)

40.86666666666667

In [24]:
np.median(x2)

38.0

In [25]:
np.var(x2)

331.44888888888886

In [26]:
#Find cumulative sum of rows in ‘x2’.
x2.cumsum(axis=0)

array([[ 32,  21,  65],
       [121,  54,  88],
       [143,  94, 109],
       [175, 150, 154],
       [219, 188, 206]])

In [27]:
#Sort the data in ‘x2’ along the columns.
sort = np.sort(x2, axis=0)
sort

array([[22, 21, 21],
       [32, 33, 23],
       [32, 38, 45],
       [44, 40, 52],
       [89, 56, 65]])

In [28]:
#Replace values greater than 40 in ‘x2’ with 0 using ‘where’ function.


In [29]:
#x2[x2 > 40] = 0
#x2

In [30]:
x2

array([[32, 21, 65],
       [89, 33, 23],
       [22, 40, 21],
       [32, 56, 45],
       [44, 38, 52]])

In [31]:
zero = np.where((x2 > 40), 0, x2)
zero


array([[32, 21,  0],
       [ 0, 33, 23],
       [22, 40, 21],
       [32,  0,  0],
       [ 0, 38,  0]])

In [32]:
#1. Consider a list of values:
bag = [25,26,21,22,31,29,33,34,26,30,31,46]
#• Import the appropriate Python libraries to create a ndarray called bag_weights
#having 3 rows and 4 columns from the list bag.
#• Use Numpy library to display the mean, variance and median of the given data in
#bag_weights.
#• Write a command to display the count of values greater than the median in
#bag_weights.
#• Transpose bag_weights and then split it in two arrays bagA and bagB having 2
#rows and three columns each.
#• Sort bagA such that it brings the highest value of the row in the first column. 
#Sort bagB such that it brings the lowest value of the row in the first column.
#• Find the union and intersection of values in bagA and bagB.

In [33]:
#Import the appropriate Python libraries to create a ndarray called bag_weights
#having 3 rows and 4 columns from the list bag.
bag_weights = np.array([bag]).reshape((3, 4))
bag_weights

array([[25, 26, 21, 22],
       [31, 29, 33, 34],
       [26, 30, 31, 46]])

In [34]:
#• Use Numpy library to display the mean, variance and median of the given data in
#bag_weights.


In [35]:
np.mean(bag_weights)

29.5

In [36]:
np.median(bag_weights)

29.5

In [37]:
np.var(bag_weights)

40.25

In [38]:
#• Write a command to display the count of values greater than the median in
#bag_weights.
median = 29.5
greater_than_median = (bag_weights > median).sum()
greater_than_median

6

In [39]:
#• Transpose bag_weights and then split it in two arrays bagA and bagB having 2
#rows and three columns each.
weights_bag = bag_weights.T
weights_bag


array([[25, 31, 26],
       [26, 29, 30],
       [21, 33, 31],
       [22, 34, 46]])

In [40]:
bagA, bagB = np.array_split(weights_bag, 2)
bagA


array([[25, 31, 26],
       [26, 29, 30]])

In [41]:
bagB

array([[21, 33, 31],
       [22, 34, 46]])

In [48]:
#Sort bagA such that it brings the highest value of the row in the first column. 
#Sort bagB such that it brings the lowest value of the row in the first column.
sorted_bagA = np.sort(bagA, axis=1)[:, ::-1]
sorted_bagA

array([[31, 26, 25],
       [30, 29, 26]])

In [49]:
np.sort(bagB)[::1]

array([[21, 31, 33],
       [22, 34, 46]])

In [44]:
#Find the union and intersection of values in bagA and bagB.
union = np.union1d(bagA, bagB)
union

array([21, 22, 25, 26, 29, 30, 31, 33, 34, 46])

In [45]:
intersection = np.intersect1d(bagA, bagB)
intersection

array([31])