In [1]:
#1 Write programs in python using NumPy library to do the following
import numpy as np



In [2]:
import pandas as pd

In [3]:
#a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along
#the second axis.
x = np.arange(6)

In [4]:
print("\nOriginal array:")



Original array:


In [5]:
print(x)

[0 1 2 3 4 5]


In [6]:
r1 = np.mean(x)

In [7]:
r2 = np.average(x)

In [8]:
assert np.allclose(r1, r2)

In [9]:
print("\nMean: ", r1)


Mean:  2.5


In [10]:
r1 = np.std(x)

In [11]:
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2 ))

In [12]:
assert np.allclose(r1, r2)

In [13]:
print("\nstd: ", 1)


std:  1


In [14]:
r1= np.var(x)

In [15]:
r2 = np.mean((x - np.mean(x)) ** 2 )

In [16]:
assert np.allclose(r1, r2)

In [17]:
print("\nvariance: ", r1)


variance:  2.9166666666666665


In [18]:
#b. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of
#the array and then reshape it into an n x m array, where n and m are user inputs given at the run time.
t1 = np.arange(1, 9).reshape(2, 4)
t1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
r = int(input("Enter the number of rows:"))



Enter the number of rows:2


In [20]:
c = int(input("Enter the number of columns:"))

Enter the number of columns:3


In [21]:
samples = np.random.standard_normal(size=(r, c))



In [22]:
print(samples)

[[ 0.52863944  0.25225422 -1.02699333]
 [ 0.87333872  0.10848857 -1.39511544]]


In [23]:
samples2 = samples.T

In [24]:
print(samples.dtype)

float64


In [25]:
print(samples.shape) 

(2, 3)


In [26]:
print(samples2)

[[ 0.52863944  0.87333872]
 [ 0.25225422  0.10848857]
 [-1.02699333 -1.39511544]]


In [27]:
#c. Test whether the elements of a given 1D array are zero, non-zero and NaN. Record the indices of these
#elements in three separate arrays.
def test_array_elements(array):
    zero_indices = np.where(array == 0)[0]
    non_zero_indices = np.where(array != 0)[0]
    nan_indices = np.where(np.isnan(array))[0]
    return zero_indices, non_zero_indices, nan_indices

In [28]:
arr = np.array([1, 0, 4, 9, np.nan, 6.8])

In [29]:
zero_indices, non_zero_indices, nan_indices = test_array_elements(arr)

In [30]:
print("Zero Indices:", zero_indices)

Zero Indices: [1]


In [31]:
print("Non Zero Indices:", non_zero_indices)

Non Zero Indices: [0 2 3 4 5]


In [32]:
print("NaN Indices:", nan_indices)

NaN Indices: [4]


In [33]:
#Create three random arrays of the same size: Array1, Array2 and Array3. Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1. 
#Find Co- variance and Correlation of Array1 with Array4 and Array5 respectively.
size=10
array1 = np.random.randint(low=0, high=10, size=size)
array2 = np.random.randint(low=0, high=10, size=size)
array3 = np.random.randint(low=0, high=10, size=size)
array1

array([8, 6, 6, 6, 9, 1, 7, 6, 7, 6])

In [34]:
array4 = array3 - array2
array4

array([-1,  7,  5,  0, -2,  3,  7, -1,  4, -6])

In [35]:
array5 = array1 * 2
array5

array([16, 12, 12, 12, 18,  2, 14, 12, 14, 12])

In [36]:
#covariance and correlation
cov4 = np.cov(array1, array4)

In [37]:
print("Covariance of array1 and array4:", cov4)

Covariance of array1 and array4: [[ 4.4        -1.68888889]
 [-1.68888889 18.26666667]]


In [38]:
cov5 = np.cov(array1, array5)

In [39]:
print("Covariance of array1 and array5:", cov5)

Covariance of array1 and array5: [[ 4.4  8.8]
 [ 8.8 17.6]]


In [40]:
cor4 = np.corrcoef(array1, array4)

In [41]:
print("Correlation of array1 and array4:", cor4)

Correlation of array1 and array4: [[ 1.         -0.18838447]
 [-0.18838447  1.        ]]


In [42]:
cor5 = np.corrcoef(array1, array5)

In [43]:
print("Correlation of array1 and array5:", cor5)

Correlation of array1 and array5: [[1. 1.]
 [1. 1.]]


In [44]:
import numpy as np

In [45]:
#Create two random arrays of the same size 10: Array1, and Array2. Find the sum of the first 
#half of both the arrays and product of the second half of both the arrays.
arr1 = np.random.randint(low=0, high=10, size=10)

In [46]:
arr2 = np.random.randint(low=0, high=60, size=10)

In [47]:
print(arr1)

[8 6 9 4 8 6 1 9 6 9]


In [48]:
print(arr2)

[ 6 13 36 34 58 59 23 37 14 30]


In [49]:
sum_first_half = np.sum(arr1[:5]) + np.sum(arr2[:5])


In [50]:
print("Sum of the first half:", sum_first_half)

Sum of the first half: 182


In [51]:
product_second_half = np.prod(arr1[5:]) * np.prod(arr2[5:])


In [52]:
print("Sum of the first half:", sum_first_half)

Sum of the first half: 182


In [53]:
print("Product of the second half:", product_second_half)

Product of the second half: 61491966480
